name: Release
on:
  push:
    tags-ignore:
      - '*.*'
    paths-ignore:
      - "app/build.gradle"
    branches:
      - master


jobs:
  publish:
    name: Release Simple Library
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
                ~/.gradle/caches
                ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Bump Version
        run: |
           chmod +x ./scripts/bump_version.sh
           ./scripts/bump_version.sh "${{ steps.previoustag.outputs.tag }}" "$(git rev-parse --short "$GITHUB_SHA")"
    
      - name: Commit changes
        run: |
           git config user.name ${{ github.actor }}
           git config user.email ${{ github.actor }}@users.noreply.gihub.com
           git add app/build.gradle
           git commit -m "[AUTOMATED] Private Release",
           git push origin


      - name: Grant Permission for Gradlew to Execute
        run: chmod +x gradlew

      - name: Build AAR ⚙️🛠
        run: bash ./gradlew :simplelibrary:assemble

      - name: Publish to GitHub Package Registry 🚀
        run: bash ./gradlew :simplelibrary:publish
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Simple Library AAR 🗳
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: simplelibrary/build/outputs/aar/simplelibrary-release.aar
          asset_name: simple-library.aar
          asset_content_type: application/aar