name: Internal Release

on:
  push:
    tags: 'v*.*.*'
    branch:
      - master
      
jobs:
  build-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0

      - name: Bump Version
        run: npm version "${{ github.event.inputs.version_number }}"

      - name: Commit changes
        run: |
           git config user.name "skyflow-tejesh-reddy"
           git config user.email "tejesh.skyflow@gmail.com"
           git add app/build.gradle
           git commit -m "[AUTOMATED] Public Release"
           git tag "${{ github.event.inputs.version_number }}"
           git push origin main

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        run: gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
